export const FETCH_PRODUCT = "FETCH_PRODUCT";
export const FETCH_ACCOUNT = "FETCH_ACCOUNT";
export const FETCH_LOGIN = "FETCH_LOGIN";
export const FETCH_LOGOUT = "FETCH_LOGOUT";
export const FETCH_IS_LOGIN = "FETCH_IS_LOGIN";
export const FETCH_INFO_USER = "FETCH_INFO_USER";
export const FETCH_SUBJECT = "FETCH_SUBJECT";
export const FETCH_LEVELCLASS = "FETCH_LEVELCLASS";
export const FETCH_STUDENTS = "FETCH_STUDENTS";
export const FETCH_CHECKED_STUDENTS = "FETCH_CHECKED_STUDENTS";
export const FETCH_UNCHECK_STUDENTS = "FETCH_UNCHECK_STUDENTS";
export const FETCH_DETAIL_STUDENTS = "FETCH_DETAIL_STUDENTS";
export const FETCH_CODE_STUDENTS = "FETCH_CODE_STUDENTS";
export const FETCH_RESET_DETAIL_STUDENTS = "FETCH_RESET_DETAIL_STUDENTS";
export const FETCH_LEVELSTUDENTS = "FETCH_LEVELSTUDENTS";

export const FETCH_CLASSROOMS = "FETCH_CLASSROOMS";
export const FETCH_LIST_STUDENT_CLASS = "FETCH_LIST_STUDENT_CLASS";
export const FETCH_CHECKED_CLASSROOMS = "FETCH_CHECKED_CLASSROOMS";
export const FETCH_UNCHECK_CLASSROOMS = "FETCH_UNCHECK_CLASSROOMS";
export const FETCH_UNCHECK_STUDENT_CLASSROOMS =
  "FETCH_UNCHECK_STUDENT_CLASSROOMS";
export const FETCH_CHECKED_STUDENT_CLASSROOMS =
  "FETCH_CHECKED_STUDENT_CLASSROOMS";
export const FETCH_DETAIL_CLASS = "FETCH_DETAIL_CLASS";
export const FETCH_CODE_CLASS = "FETCH_CODE_CLASS";
export const FETCH_RESET_DETAIL_CLASSROOMS = "FETCH_RESET_DETAIL_CLASSROOMS";
export const FETCH_CLASS_BY_STUDENT = "FETCH_CLASS_BY_STUDENT";
export const FETCH_TABLE_POINTS_STUDENT = "FETCH_TABLE_POINTS_STUDENT";
export const FETCH_TABLE_POINT_STUDENT_CLASS_SUBJECT =
  "FETCH_TABLE_POINT_STUDENT_CLASS_SUBJECT";
export const FETCH_INFOPOINT_STUDENT_CLASS_SUBJECT =
  "FETCH_INFOPOINT_STUDENT_CLASS_SUBJECT";
